### ISSUE TITLE
Error with undefined _styleObservers object

### ISSUE THREAD

**Issue by knownasilya** [miguelcobain/ember-leaflet#152]
When using version 3.0.10 (can't upgrade since later versions use leaflet 1.x, but I need Carto support). Seems like the style observer gets torn down before it's set up. That object might need to be defined at another part of the lifecycle.

> ember.debug.js:18015 TypeError: Cannot read property 'stroke' of undefined
    at Class.<anonymous> (http://localhost:5000/assets/vendor.js:140174:65)
    at Array.forEach (native)
    at Class._removeStyleObservers (http://localhost:5000/assets/vendor.js:140173:42)
    at Class.willDestroyParent (http://localhost:5000/assets/vendor.js:140155:12)
    at Class.superWrapper [as willDestroyParent] (http://localhost:5000/assets/vendor.js:60328:22)
    at Array.<anonymous> (http://localhost:5000/assets/vendor.js:53365:36)
    at Array.forEach (native)
    at Array.invoke (http://localhost:5000/assets/vendor.js:53361:12)
    at Class.destroyChildren (http://localhost:5000/assets/vendor.js:110083:28)
    at Class.destroySelfAndChildren (http://localhost:5000/assets/vendor.js:110073:12)

Happens when rerendering a list like:

```hbs
{{#each sites as |site|}}
  {{#if site.geoJSON}}
    {{#geojson-layer geoJSON=site.geoJSON color='#e56c2d' onAdd=onAdd dashArray='5, 10' fillOpacity=0.1}}
      {{#popup-layer}}
        <div>
          {{site.siteName}}
        </div>
        <div>
          {{#link-to 'account.property' site.siteType site.id}}View Property{{/link-to}}
        </div>
      {{/popup-layer}}
    {{/geojson-layer}}
  {{/if}}
{{/each}}
```

**Comment by miguelcobain** [comment]
@knownasilya we made sure that you can still use leaflet 0.7. Read installation section: https://github.com/miguelcobain/ember-leaflet#installation

Not sure if it solves this problem, though.

**Comment by knownasilya** [comment]
@miguelcobain ah, thanks for pointing that out. Unfortunately, it didn't solve the issue.

**Comment by knownasilya** [comment]
This is still a persisting issue. Any thoughts?

**Comment by knownasilya** [comment]
I think ember-state-services would be a good solution for this state management. Seems like there is a leak since the component is reused.

**Comment by knownasilya** [comment]
It's a bug in composability-tools for sure, seems like `willDestroyParent` is called multiple times.

Error during pagination use-case:

1. Open page 1
2. Open page 2, page 1 items willDestroyParent called
3. Open page 1, page 1 items willDestroyParent called again..

Seems like some cleanup or logic isn't working right.
