### ISSUE TITLE
Infinite rerender invalidation

### ISSUE THREAD

**Issue by knownasilya** [miguelcobain/ember-leaflet#176]
Still receiving issues like this, especially when changing out lots of layers dynamically via some kind of toggle.

> Error: infinite rendering invalidation detected
    at Array.loopEnd (http://localhost:4200/assets/vendor.js:41646:17)
    at Backburner._trigger (http://localhost:4200/assets/vendor.js:32599:33)
    at Backburner.end (http://localhost:4200/assets/vendor.js:32209:26)
    at Backburner.run (http://localhost:4200/assets/vendor.js:32279:26)
    at run$1 (http://localhost:4200/assets/vendor.js:49888:27)
    at Class._eventHandlers.(anonymous function) (http://localhost:4200/assets/vendor.js:130717:11)
    at NewClass.fire (http://localhost:4200/assets/vendor.js:79740:11)
    at NewClass._layerAdd (http://localhost:4200/assets/vendor.js:83154:8)
    at NewClass.whenReady (http://localhost:4200/assets/vendor.js:82790:13)
    at NewClass.addLayer (http://localhost:4200/assets/vendor.js:83206:8)

![screen shot 2017-09-12 at 4 17 43 pm](https://user-images.githubusercontent.com/34726/30346186-f6ecb89e-97d5-11e7-9f4e-047cbb8bc02a.png)

**Comment by devotox** [comment]
@knownasilya not a fix but ive found that using Ember.run.next in certain places can at least stop the error in your code. I had the same issue using the onZoomend action which is a problem on the initial render

**Comment by jayvarner** [comment]
I'm getting this when I add more than 10 features with an `onAdd` listener. Here's a [Twiddle](https://ember-twiddle.com/bcd6a54cf32ebd5670a32a433b9111ff?openFiles=controllers.application.js%2C). It works if you remove one from the points array. Note: I could only get ember-leaflet to work with 2.13 on Twiddle. I'm getting this same error on 2.18.

Twiddle: https://ember-twiddle.com/bcd6a54cf32ebd5670a32a433b9111ff?openFiles=controllers.application.js%2C

Error: 
<img width="818" alt="screenshot 2018-03-20 13 11 35" src="https://user-images.githubusercontent.com/24685/37670690-519fba58-2c40-11e8-8a44-a15713429965.png">

**Comment by miguelcobain** [comment]
Should be fixed. Please reopen if still a concern.
