### ISSUE TITLE
NPE: TypeError: this.L.latLng is not a function in fastboot

### ISSUE THREAD

**Issue by gossi** [miguelcobain/ember-leaflet#676]
Heyo,

while trying  prember (through fastboot), I got this error in my console:

```sh
There was an error running your app in fastboot. More info about the error:
 TypeError: this.L.latLng is not a function
    at LeafletMap.get center [as center] (/var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:87918:23)
    at _getProp (/var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:11832:20)
    at /var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:42673:45
    at /var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:42621:37
    at track (/var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:52210:7)
    at valueForRef (/var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:42620:44)
    at PositionalArgsProxy.get (/var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:37860:43)
    at Proxy.forEach (<anonymous>)
    at DidUpdateHelper.compute (/var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:90339:20)
    at ClassicHelperManager.getValue (/var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:6141:26)
    at /var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:38427:70
    at /var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:42621:37
    at track (/var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:52210:7)
    at valueForRef (/var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:42620:44)
    at Object.evaluate (/var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:46970:60)
    at AppendOpcodes.evaluate (/var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:44267:19)
    at LowLevelVM.evaluateSyscall (/var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:48133:22)
    at LowLevelVM.evaluateInner (/var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:48089:14)
    at LowLevelVM.evaluateOuter (/var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:48081:14)
    at VM.next (/var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:49092:24)
    at VM._execute (/var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:49076:23)
    at VM.execute (/var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:49067:21)
    at TemplateIteratorImpl.sync (/var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:49151:24)
    at RootState.render (/var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:8449:45)
    at /var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:8770:18
    at inTransaction (/var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:47975:9)
    at Renderer._renderRoots (/var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:8750:36)
    at Renderer._renderRootsTransaction (/var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:8802:14)
    at Renderer._renderRoot (/var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:8737:12)
    at Renderer._appendDefinition (/var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:8644:12)
    at Renderer.appendOutletView (/var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:8626:12)
    at invokeWithOnError (/var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:53280:18)
    at Queue.flush (/var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:53159:13)
    at DeferredActionQueues.flush (/var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:53365:21)
    at Backburner._end (/var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:53917:34)
    at Backburner._boundAutorunEnd (/var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/broccoli-95034l4tHYCKwEMIR/out-425-broccoli_merge_trees/assets/vendor.js:53566:14)
```

I could trace it down to this line: https://github.com/miguelcobain/ember-leaflet/blob/f9aad2165a8f8e7ea4431f6a195dacd5b971854d/addon/components/leaflet-map.js#L709

I'm using this code to include the map:

```hbs
<LeafletMap
  @lat={{45.519743}}
  @lng={{-122.680522}}
  @zoom={{10}}
  local-class="map"
  as |layers|
>
  <layers.tile
    @url="https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png"
  />

  <layers.marker @location={{array 45.528298 -122.662986}} as |marker|>
    <marker.popup>
      text...
    </marker.popup>
  </layers.marker>
</LeafletMap>
```

Would be nice to have this error free, for happy CIs during prember deploys :)

Thank you

**Comment by miguelcobain** [comment]
Fix released on version `5.0.1`. Please reopen if issue persists.
Thanks for reporting!
