### ISSUE TITLE
Error on cleanup

### ISSUE THREAD

**Issue by kmccullough** [miguelcobain/ember-leaflet#679]
Running on ember@3.28.9, leaflet@1.8.0, and ember-leaflet@5.0.1 and seeing a similar issue to https://github.com/miguelcobain/ember-leaflet/issues/195 when leaving the route.

```
base-layer.js:284 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'removeEventListener')
    at LeafletMap._removeEventListeners (base-layer.js:284:1)
    at LeafletMap.willDestroyParent (base-layer.js:205:1)
    at LeafletMap.willDestroyParent (leaflet-map.js:706:1)
    at Root.teardown (node.js:128:1)
    at Root.willDestroyNode (node.js:99:1)
    at will-destroy.js:23:1
    at invoke (backburner.js:353:1)
    at Queue.flush (backburner.js:241:1)
    at DeferredActionQueues.flush (backburner.js:447:1)
    at Backburner._end (backburner.js:999:1)
```

**Comment by jelhan** [comment]
Can you still reproduce the error on recent versions? If so, please share a reproduction.

**Comment by kmccullough** [comment]
@jelhan We upgraded to ember-leaflet 5.1.3 and no longer see this issue.
