### ISSUE TITLE
Uncaught Error: Assertion Failed: The `element` helper polyfill encountered an unexpected error

### ISSUE THREAD

**Issue by glbatistabh** [miguelcobain/ember-leaflet#681]
Hi! Please can someone help me with this error?
I can't solve it and I'm thinking it's a bug.

**Error:**
```
Uncaught Error: Assertion Failed: The `element` helper polyfill encountered an unexpected error. Please report the issue at http://github.com/tildeio/ember-element-helper with the usage and conditions that caused this error.
    at assert (index.js:181:1)
    at element.js:14:1
    at index.js:5258:1
    at deprecateMutationsInTrackingTransaction (validator.js:191:1)
    at index.js:5257:1
    at SimpleClassicHelperManager.getValue (index.js:5268:1)
    at manager.js:971:1
    at reference.js:170:1
    at track (validator.js:835:1)
    at valueForRef (reference.js:169:1)
```

**package.json**
```
shell>cat package.json | grep leaflet
    "ember-leaflet": "^5.0.1",
    "leaflet": "^1.8.0",
```

**Environment:**
```
shell>ember -v
ember-cli: 3.28.5
node: 14.15.5
os: linux x64
```

**Printscreen:**
![image](https://user-images.githubusercontent.com/8257020/190023885-67e52ed1-59cb-411b-9251-645d49a9dcee.png)

**Comment by KroneckerDeIta** [comment]
You've probably fixed this issue by now, but for others...

I just ran into this issue and I think it is because your ember-element-helper library is too old. Looking in the package-lock.json file for ember-leaflet it looks like it expects it to be at version 0.6.0 (mine was at 0.5.5). Look in your package-lock.json file to see what is setting that to an older version (for me it was an older version of ember-power-select). When I had bumped the version of libraries it worked ok.

**Comment by miguelcobain** [comment]
@KroneckerDeIta thank you for your input.

Yes, transitive dependencies in ember can be tricky, because only one version "wins" in the build.

I will close this as this isn't an issue with ember-leaflet itself.
